//
// Created by Fabio Villalobos on 25/8/2020.
//

#ifndef MY_PROJECT_NAME_IMAQUINAADMINISTRRADORA_H
#define MY_PROJECT_NAME_IMAQUINAADMINISTRRADORA_H


class IMaquinaAdministrradora {

};


#endif //MY_PROJECT_NAME_IMAQUINAADMINISTRRADORA_H
